#!/bin/bash

# USAGE:
# - Ensure env variables are set to find USD installation.
# - ./with_plugin usdview ../src/data/test/00.usdx

export MOPR_TEST_ROOT=`realpath $0 | xargs -0 dirname`

# Based on info in usd/BUILDING.md
export PXR_PLUGINPATH_NAME=${MOPR_TEST_ROOT}/usdx/:${PXR_PLUGINPATH_NAME}

export LD_LIBRARY_PATH=${MOPR_TEST_ROOT}/lib:${LD_LIBRARY_PATH}

export TF_DEBUG="PLUG_LOAD SDF_FILE_FORMAT SDF_LAYER"

echo Running with:
echo "  PXR_PLUGINPATH_NAME : ${PXR_PLUGINPATH_NAME}"
echo "  TF_DEBUG            : ${TF_DEBUG}"
exec "$@"
